version: '3.8'

services:
 web:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - 3000:80
   develop:
     watch:
       - path: .
         target: /usr/share/nginx/html
         action: sync+restart

volumes:
 tasked:
